=== pndni/PipelineQC/PipelineQC/schema/config.json
{
    "$schema": "http://json-schema.org/schema$",
    "type": "object",
    "required": ["page_keys", "page_filename_template", "index_filename", "patterns", "files", "reportlets"],
    "properties": {
        "page_keys": {
            "type": "array",
            "items": {
                "type": "string",
        "pattern": "^[a-zA-Z0-9]*$"
            }
        },
        "page_filename_template": {
            "type": "string",
        "pattern": "^([^][]*(\\[[^][}{]*\\{[a-zA-Z0-9]*\\}[^][}{]*\\]*)*)*$"
        },
        "index_filename": {
            "type": "string"
        },
        "patterns": {
            "type": "object",
            "patternProperties": {
                ".*": {
                    "type": "string"
                }
            }
        },
        "files": {
            "type": "object",
            "patternProperties": {
                ".*": {
                    "type": "object",
                    "required": ["pattern", "filter"],
                    "properties": {
                        "pattern": {
                            "type": "string"
                        },
                        "filter": {
                            "type": "object"
                        },
                        "global": {
                            "type": "boolean"
                        },
                        "allow_multiple": {
                            "type": "boolean"
                        }
                    }
                }
            }
        },
        "reportlets": {
            "type": "array",
            "items": {
                "type": "object",
                "additionalProperties": false,
                "required": ["type"],
                "properties": {
                    "type": {
                        "type": "string",
                        "enum": ["single", "contour", "compare", "distributions", "crash"]
                    },
                    "qcform": {
                        "type": "boolean"
                    },
                    "nslices": {
                        "type": "integer"
                    }
                },
                "allOf": [
                    {
                        "if": {
                            "properties": { "type": { "const": "single" } }
                        },
                        "then": {
                            "properties": {
                                "name": {
                                    "type": "string"
                                },
                                "image": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    {
                        "if": {
                            "properties": { "type": { "const": "compare" } }
                        },
                        "then": {
                            "properties": {
                                "name1": {
                                    "type": "string"
                                },
                                "image1": {
                                    "type": "string"
                                },
                                "name2": {
                                    "type": "string"
                                },
                                "image2": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    {
                        "if": {
                            "properties": { "type": { "const": "contour" } }
                        },
                        "then": {
                            "properties": {
                                "name": {
                                    "type": "string"
                                },
                                "image": {
                                    "type": "string"
                                },
                                "labelimage": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    {
                        "if": {
                            "properties": { "type": { "const": "distributions" } }
                        },
                        "then": {
                            "properties": {
                                "distsfile": {
                                    "type": "string"
                                },
                                "labelfile": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    {
                        "if": {
                            "properties": { "type": { "const": "crash" } }
                        },
                        "then": {
                            "properties": {
                                "crashfiles": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ]
            }
        }
    }
}

=== pndni/PipelineQC/tests/testconf1bids2.json
{
    "page_keys": ["subject", "acquisition", "reconstruction", "run", "session"],
    "page_filename_template": "sub-{subject}[/ses-{session}]/sub-{subject}[_ses-{session}][_acq-{acquisition}][_rec-{reconstruction}][_run-{run}]_QC.html",
    "index_filename": "QC_index.html",
    "patterns": {
        "simple": "(?P<base>.*)\\.(?P<extension>.*)",
        "crash": "sub-(?P<subject>[a-zA-Z0-9]+)(/ses-(?P<session>[a-zA-Z0-9]+))?/logs/sub-(?P=subject)(_ses-(?P=session))?(_acq-(?P<acquisition>[a-zA-Z0-9]+))?(_rec-(?P<reconstruction>[a-zA-Z0-9]+))?(_run-(?P<run>[0-9]+))?/crash.*\\.pklz",
	"bids": [
	    "bids",
	    "derivatives", 
	    {
		"name": "pndni_bids",
		"entities": [
		    {
			"name": "skullstripped",
			"pattern": "[_/\\\\]+skullstripped-([a-zA-Z0-9]+)"
		    },
		    {
			"name": "map",
			"pattern": "[_/\\\\]+map-([a-zA-Z0-9]+)"
		    },
		    {
			"name": "presuffix",
			"pattern": "_([a-zA-Z0-9]*?)_[a-zA-Z0-9]*?\\.[^/\\\\]+$"
		    }
		]
	    }
	]
    },
    "files": {
        "model": {
            "pattern": "simple",
            "filter": {"base": "model"},
            "global": true
        },
        "T1w": {
            "pattern": "bids",
            "filter": {"suffix": "T1w", "space": null, "desc": null}
        },
        "nu_bet": {
            "pattern": "bids",
            "filter": {"desc": "nucor"}
        },
        "normalized": {
            "pattern": "bids",
            "filter": {"desc": "normalized"}
        },
        "warped_model": {
            "pattern": "bids",
            "filter": {"space": "T1w", "suffix": "T1w"}
        },
        "features": {
            "pattern": "bids",
            "filter": {"suffix": "features", "extension": "txt"}
        },
        "features_label": {
            "pattern": "bids",
            "filter": {"presuffix": "features", "suffix": "labels", "extension": "tsv"}
        },
        "classified": {
            "pattern": "bids",
            "filter": {"suffix": "dseg", "desc": "tissue"}
        },
        "transformed_atlas": {
            "pattern": "bids",
            "filter": {"suffix": "dseg", "desc": "lobes"}
        },
        "crashfiles": {
            "pattern": "crash",
            "filter": {},
            "allow_multiple": true
        }
    },
    "reportlets": [
    ]
}

=== pndni/PipelineQC/tests/testconf2.json
{
    "page_keys": ["sub"],
    "page_filename_template": "sub-{sub}[/ses-{ses}]/sub-{sub}[_ses-{ses}][_acq-{acq}][_rec-{rec}][_run-{run}]_QC.html",
    "index_filename": "QC_index.html",
    "patterns": {
        "derivatives": "(?P<dir>[^/]+)/(?P<sub>sub[0-9]+_[0-9]+)[0-9_]*mri(_(?P<suffix>.*))?\\.(?P<extension>.*)"
    },
    "files": {
        "T1w": {
            "pattern": "derivatives",
            "filter": {"dir": "orig"}
        },
        "bet": {
            "pattern": "derivatives",
            "filter": {"suffix": "bet"}
        },
        "normalized": {
            "pattern": "derivatives",
            "filter": {"suffix": "normalized"}
        },
        "features": {
            "pattern": "derivatives",
            "filter": {"extension": "tag"}
        },
        "classified": {
            "pattern": "derivatives",
            "filter": {"suffix": "classify"}
        },
        "transformed_atlas": {
            "pattern": "derivatives",
            "filter": {"dir": "transformed", "suffix": "atlasRes"}
        }
    },
    "reportlets": []
}
